### ISSUE TITLE
Ubuntu gnome desktop file name

### ISSUE THREAD

**Issue by bios-ben** [pbek/QOwnNotes#1019]
#### Expected behaviour
Add to favorites button works in ubuntu 18.
#### Actual behaviour
Add to favorites missing.
#### Steps to reproduce
Open app and right click in dock to see missing menu, try renaming solution and now it shows.
#### Version 18.09.01

After reading [stack exchange](https://unix.stackexchange.com/questions/58824/how-do-i-add-eclipse-to-my-gnome-shell-favorites) I found that desktop links cannot be added to favorites unless their file name matches the window name. Checking into this it seems the file is named PBE.QOwnNotes.desktop and when renamed to QOwnNotes.desktop the problem is fixed, as per the above link. However, I did find #933 that caused this rename to happen in the first place. Is it possible to get the default desktop link named properly to work in ubuntu?

**Comment by pbek** [comment]
You have researched the problem pretty well. Unfortunately I have no secret information on how to make it work in both conditions, please let me know if you find anything out!

**Comment by PaulVanSchayck** [comment]
I also ran into this, and can confirm this temporary workaround:
```
sudo mv /usr/share/applications/PBE.QOwnNotes.desktop /usr/share/applications/QOwnNotes.desktop
```

**Comment by pbek** [comment]
That was the previous name, see #933.
I will try adding `StartupWMClass=QOwnNotes` to the desktop file in the next release. Can you please try using the `PBE.QOwnNotes.desktop` and adding above line to it and report if that works.

**Comment by PaulVanSchayck** [comment]
Yup, this also seems to works! Thanks for that

**Comment by pbek** [comment]
awesome!

**Comment by pbek** [comment]
## 18.10.3
- fixed QOwnNotes favorite button in Gnome dash

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by OtharSmirnow** [comment]
On Ubuntu it does not work as expected.
![obraz](https://user-images.githubusercontent.com/7104087/71241952-16a9df80-230d-11ea-8507-4bec474289bc.png)
I will update if any of workarounds above works

**Comment by pbek** [comment]
> On Ubuntu it does not work as expected.
> ![obraz](https://user-images.githubusercontent.com/7104087/71241952-16a9df80-230d-11ea-8507-4bec474289bc.png)
> I will update if any of workarounds above works

Where did you install QOwnNotes from? Can you please post the output from the debug settings (see issue template).

**Comment by OtharSmirnow** [comment]
Installed snap from Ubuntu Software:
Channel: Stable
Version: 19.12.13
Last Update: 18.12.2019
Developer: Patrizio Bekerle


[QOwnNotes.log](https://github.com/pbek/QOwnNotes/files/3988088/QOwnNotes.log)

**Comment by pbek** [comment]
I'm not sure how Gnome (or are you using Unity) is handling desktop files from snaps. If you are using the stable channel this desktop file is used: https://github.com/pbek/QOwnNotes/blob/develop/snap/gui/PBE.QOwnNotes.desktop

**Comment by pbek** [comment]
Could you test the Ubuntu PPA, AppImage or Flatpack of QOwnNotes if you have the same problem? see https://www.qownnotes.org/installation

**Comment by OtharSmirnow** [comment]
I am running Ubuntu 19.10 with Gnome

Tested AppImage - same story.

I created a .desktop file with Arronax and it worked well(placed in /usr/share/applications), but I wasn't able to edit the one in snap.
[Desktop Entry]
Type=Application
Icon=folder-copy
Name=QOwnNotes-test
Exec=qownnotes
Terminal=false
Hidden=false
Categories=Office; Utility
StartupWMClass=QOwnNotes
Comment=test

may be unrelated:
when starting from terminal I got this
`Warning: Qt: Session management error: None of the authentication protocols specified are supported ((null):0, (null))
Warning: propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.758\" (uid=1000 pid=12069 comm=\"/snap/qownnotes/4219/usr/bin/QOwnNotes -style=Fusi\" label=\"snap.qownnotes.qownnotes (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1372 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")" ((null):0, (null))
Warning: nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.758\" (uid=1000 pid=12069 comm=\"/snap/qownnotes/4219/usr/bin/QOwnNotes -style=Fusi\" label=\"snap.qownnotes.qownnotes (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1372 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")" ((null):0, (null))
Warning: "Object path cannot be empty" ((null):0, (null))
Warning: Unable to find dictionary for "pl_PL" in path "/pl_PL" ((null):0, (null))
Info: "Serwer QOwnNotes oczekuje na połączenia na porcie 22222" ((null):0, (null))`

**Comment by datumbox** [comment]
Same problem on Gnome 3.36.3 while using the snap version (20.8.10). Could we reopen the ticket given that the problem persists?

**Comment by pbek** [comment]
Doesn't make a lot difference as long nobody knows how to fix it. 😁

**Comment by datumbox** [comment]
If there is anything I can do to help debug I'm more than happy to help. Let me know.

**Comment by pbek** [comment]
The only thing that comes to mind is to play with the desktop file or research how the favorites work.

**Comment by datumbox** [comment]
Here is an ugly workaround. If you rename the file `qownnotes_PBE.QOwnNotes.desktop` to `qownnotes_qownnotes.desktop` it works fine. This is located in `/var/lib/snapd/desktop/applications/` and also in your `~/.local/share/applications/` if you have custom shortcuts. No other desktop file needs to be modified.

The way I found this was by observing the naming convention of the desktop files of all of my snaps. Any snap with desktop file not named like `{snapname}_{snapname}.desktop` has exactly the same problem (excluding the ubuntu snap store which I don't understand why it works).

@pbek Is the naming you are using valid? If yes, looks like an upstream problem as you hinted originally.

**Comment by pbek** [comment]
I guess snapcraft chose that name. The original file that is used is <https://github.com/pbek/QOwnNotes/blob/develop/build-systems/snap/snapcraft/snap/gui/PBE.QOwnNotes.desktop>

**Comment by pbek** [comment]
And as far as I know if the name is changed it invalidates all links to desktop files... 😬

**Comment by datumbox** [comment]
Do you have a snapcraft account to raise the question in their forums and see if there is a workaround or proposed solution? Skypeforlinux snap has exactly the same problem BTW so your app is definitely not the only one affected. If you don't let me know and I'll raise it for you.

**Comment by pbek** [comment]
I could, but I don't have a Gnome system around to test/confirm and I'm not sure what will happen with #933 if I rename the file again.

**Comment by pbek** [comment]
#1713 seems similar, but also seems to be fixed

**Comment by pbek** [comment]
@datumbox, I tried to rename the desktop file in the edge channel (currently building) to `qownnotes.desktop`, hoping it will then have the correct name later on. Could you please try the edge snap?

**Comment by datumbox** [comment]
@pbek Did you push it to stable by accident? It seems that stable is newer than edge:
```
$ snap info qownnotes
.....
channels:
  latest/stable:    20.9.1  2020-09-01 (7379) 130MB -
  latest/candidate: ↑                               
  latest/beta:      ↑                               
  latest/edge:      20.8.10 2020-08-31 (7371) 127MB -
```

At any case, I tested the both the stable and edge but I don't see the file renamed. The desktop file in `/var/lib/snapd/desktop/applications` is still `qownnotes_PBE.QOwnNotes.desktop` in both versions. As a result when I open the app, I still see the same problem.

Happy to test further if you want.

**Comment by pbek** [comment]
Seems like the edge build didn't trigger on https://snapcraft.io/build. I triggered the build manual now...Should be done in maybe 25min.

**Comment by OtharSmirnow** [comment]
just changed channel to edge.
it does work correctly now. Thank you :)
When you change it in stable?

**Comment by pbek** [comment]
Ah, thank you. 

> When you change it in stable?

Next release.

**Comment by datumbox** [comment]
@pbek Yeap, works like a charm! Thanks for fixing it. :)

**Comment by pbek** [comment]
## 20.9.2
- the desktop file of the snap release of QOwnNotes was renamed to `qownnotes.desktop`
  to prevent problems with Gnome

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by datumbox** [comment]
I just checked it and it works just fine. I think we can close the tickets. Thanks a lot for looking into this.

**Comment by datumbox** [comment]
@pbek I installed the snap from latest/stable 20.9.2 2020-09-03 (7389).

Now I see two files stored in `/var/lib/snapd/desktop/applications`. One is named `qownnotes_qownnotes.desktop` and one `qownnotes_PBE.QOwnNotes.desktop`. This causes two duplicate icons of the app to appear on gnome applications dashboard. 

Is having two desktop files intentional? Can we lose the `qownnotes_PBE.QOwnNotes.desktop`?

**Comment by pbek** [comment]
Maybe that desktop file was there before and wasn't removed by the snap update, there should only be one. What happens if you uninstall QOwnNoets? Is there still that desktop file? If yes, can you please remove it and install QOwnNotes again.

**Comment by datumbox** [comment]
No the file is being installed from scratch; it's not a left over from an earlier installation. Here is what I see:

- Uninstalling the snap completely removes both files.
- Installing the snap from scratch installs both files.

I'm using the stable channel this time. Perhaps one of the other [install scripts](https://github.com/pbek/QOwnNotes/search?q=PBE.QOwnNotes.desktop&unscoped_q=PBE.QOwnNotes.desktop) is triggered and installs both files?

Happy to investigate more.

**Comment by pbek** [comment]
> Perhaps one of the other install scripts is triggered and installs both files?

Those are for other build systems.

But I see the original `PBE.QOwnNotes.desktop` get installed by snap with the `QOwnNotes.pro` install routine:
https://launchpadlibrarian.net/496188886/buildlog_snap_ubuntu_bionic_amd64_qownnotes_BUILDING.txt.gz

But that also seems to happen on the edge channel's build process:
https://snapcraft.io/qownnotes/builds/1106554 (I think you might have no permissions to view this).

So did you have the same issue on the edge channel?

**Comment by pbek** [comment]
And for what I see also in the past there always seems that two desktop files might be the desktop files around inside the snap. But I'm not sure why/if they are also made available outside the snap...

**Comment by datumbox** [comment]
@pbek I think you are right. It's likely it happened on the edge channel yesterday and we did not notice. I caught it today because I decided to do a full reinstall to check it end-to-end.

But before your commit that renames the file, I am confident though that there was only one file in `/var/lib/snapd/desktop/applications`.

**Comment by pbek** [comment]
And that one file was `qownnotes_PBE.QOwnNotes.desktop`?

What's the content of the current two files?

**Comment by datumbox** [comment]
That's correct.

They are identical with only difference their name in the exec record:

```
$ diff /var/lib/snapd/desktop/applications/qownnotes_PBE.QOwnNotes.desktop /var/lib/snapd/desktop/applications/qownnotes_qownnotes.desktop
5c5
< Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/qownnotes_PBE.QOwnNotes.desktop /snap/bin/qownnotes
---
> Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/qownnotes_qownnotes.desktop /snap/bin/qownnotes
```

**Comment by pbek** [comment]
That's interesting. It seems snapcraft took the desktop file that should be used plus the [original one](https://github.com/pbek/QOwnNotes/blob/develop/src/QOwnNotes.pro>), but modified the original one to use the correct path in the snap. I don't know yet how to prevent snapcraft using the original one.

**Comment by pbek** [comment]
@datumbox can you please install the edge snap again and confirm that there are two desktop icons too, so I have a space to test new fixes.

**Comment by pbek** [comment]
@datumbox, you can skip above comment and go straight to the 20.9.3 (stable) release to test

## 20.9.3
- the deployment of the original desktop file is now prohibited when building a
  snap with snapcraft to prevent two desktop files being deployed with the snap

**Comment by datumbox** [comment]
@pbek Unfortunately the problem persists:

```
$ sudo snap remove qownnotes 
qownnotes removed

$ ls -lh /var/lib/snapd/desktop/applications/*qown*
ls: cannot access '/var/lib/snapd/desktop/applications/*qown*': No such file or directory

$ sudo snap install qownnotes
qownnotes 20.9.3 from Patrizio Bekerle (pbek) installed

$ ls -lh /var/lib/snapd/desktop/applications/*qown*
-rwxr-xr-x 1 root root 417 Sep  6 09:51 /var/lib/snapd/desktop/applications/qownnotes_PBE.QOwnNotes.desktop
-rwxr-xr-x 1 root root 413 Sep  6 09:51 /var/lib/snapd/desktop/applications/qownnotes_qownnotes.desktop

$ diff /var/lib/snapd/desktop/applications/qownnotes_PBE.QOwnNotes.desktop /var/lib/snapd/desktop/applications/qownnotes_qownnotes.desktop
5c5
< Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/qownnotes_PBE.QOwnNotes.desktop /snap/bin/qownnotes
---
> Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/qownnotes_qownnotes.desktop /snap/bin/qownnotes

```

**Comment by pbek** [comment]
That's strange. There is no `.desktop` file deployed in <https://launchpadlibrarian.net/496503235/buildlog_snap_ubuntu_bionic_arm64_qownnotes_BUILDING.txt.gz>.

**Comment by datumbox** [comment]
It is still in there: 

- Download the actual [snap file](https://api.snapcraft.io/api/v1/snaps/download/0Zs2bQCe724ZzBFiMYAYESxhhx85hj0W_7403.snap) deployed. (Read [here](https://askubuntu.com/questions/1075694/how-to-get-snap-download-url) how to get the URLs of your binaries)
- Uncompress the snap file (you can use Archive Manager or something similar).
- Check `/meta/gui/` in the archive. You will see two desktop files: `PBE.QOwnNotes.desktop` and `qownnotes.desktop`

Screenshot:
![screenshot](https://i.ibb.co/LxGjCVM/Screenshot-from-2020-09-06-11-47-57.png)

**Comment by pbek** [comment]
Thank you for confirming! I really wonder who puts it in there and why...

**Comment by datumbox** [comment]
@pbek I think Snap picks up the `PBE.QOwnNotes.desktop` file because it is in the `src` directory of the build.

I found this article in the [documentation](https://snapcraft.io/docs/desktop-menu-icon-support#heading--desktop-key) that explains where the desktop files can be deployed. Apparently it also supports getting it from your prime directory.

Unfortunately I have not released myself any application using snaps to tell you how you could blacklist the deployment of specific files. It's worth asking the people at snapcraft. Hopefully it's straightforward.

**Comment by pbek** [comment]
@datumbox, can you please try the current build from the edge channel.

**Comment by datumbox** [comment]
@pbek You fixed it!!! :D Thanks a lot for your help!

**Comment by pbek** [comment]
Oh man, that was a hard one. Thank you for testing. Then I will try to do the same for the production snap for the next release.

**Comment by pbek** [comment]
What version number did you see when running QOwnNotes?

**Comment by datumbox** [comment]
Based on the terminal messages I installed 20.9.4.

Here is the full output for the shake of completeness:
```
$ sudo snap remove qownnotes 
qownnotes removed

$ ls -lh /var/lib/snapd/desktop/applications/*qown*
ls: cannot access '/var/lib/snapd/desktop/applications/*qown*': No such file or directory


$ sudo snap install qownnotes --channel=latest/edge
qownnotes (edge) 20.9.4 from Patrizio Bekerle (pbek) installed

$ ls -lh /var/lib/snapd/desktop/applications/*qown*
-rwxr-xr-x 1 root root 413 Sep  9 21:08 /var/lib/snapd/desktop/applications/qownnotes_qownnotes.desktop
```

One desktop file as expected.

**Comment by pbek** [comment]
Ok thank you, I almost feared that QON wasn't built at all because of the `override-build` config. 😁

**Comment by datumbox** [comment]
No worries. Ping me when you do the final release to test one more time if you want.

**Comment by pbek** [comment]
## 20.9.4
- the original desktop file is now removed while building a snap with snapcraft to prevent
  two desktop files being deployed with the snap

**Comment by pbek** [comment]
There now is a new (stable) release of the snap building, could you please test it and report if it works for you?

**Comment by datumbox** [comment]
I don't see 20.9.4 on stable yet:
```
$ snap info qownnotes 
.......
channels:
  latest/stable:    20.9.3 2020-09-06 (7403) 130MB -
  latest/candidate: ↑                              
  latest/beta:      ↑                              
  latest/edge:      20.9.4 2020-09-09 (7416) 125MB -
```

I'll check again later.

**Comment by datumbox** [comment]
@pbek I still don't see v20.9.4 on stable. Did the release went through?

**Comment by pbek** [comment]
Very strange, it failed to build on Launchpad with `rm: cannot remove 'src/PBE.QOwnNotes.desktop': No such file or directory`.

https://launchpadlibrarian.net/497062362/buildlog_snap_ubuntu_bionic_amd64_qownnotes_BUILDING.txt.gz

**Comment by pbek** [comment]
Ah, there is another file structure in the release archive. Silly me. Will be fixed in the next release. 😄

**Comment by pbek** [comment]
## 20.9.5
- fixed removal of the original desktop file while building a snap with snapcraft to prevent
  two desktop files being deployed with the snap

**Comment by pbek** [comment]
There now is a new (stable) release of the snap building, could you please test it and report if it works for you?

**Comment by datumbox** [comment]
It seems the duplicate file is back. :( What changed since 20.9.4?

```
$ sudo snap remove qownnotes 
qownnotes removed

$ ls -lh /var/lib/snapd/desktop/applications/*qown*
ls: cannot access '/var/lib/snapd/desktop/applications/*qown*': No such file or directory

$ sudo snap install qownnotes
qownnotes 20.9.5 from Patrizio Bekerle (pbek) installed

$ ls -lh /var/lib/snapd/desktop/applications/*qown*
-rwxr-xr-x 1 root root 417 Sep 13 10:04 /var/lib/snapd/desktop/applications/qownnotes_PBE.QOwnNotes.desktop
-rwxr-xr-x 1 root root 413 Sep 13 10:04 /var/lib/snapd/desktop/applications/qownnotes_qownnotes.desktop
```

**Comment by datumbox** [comment]
I noticed that the revision 7432 which is on edge does NOT have this problem and it deploys only 1 desktop file.

First of all let's check the versions:
```
$ snap info qownnotes 
....
channels:
  latest/stable:    20.9.5 2020-09-13 (7428) 125MB -
  latest/candidate: ↑                              
  latest/beta:      ↑                              
  latest/edge:      20.9.5 2020-09-13 (7432) 125MB -
```
Despite both having version 20.9.5, the latest/edge has a new revision. So they are not the same.

Let's install it:
```
$ sudo snap remove qownnotes 
qownnotes removed

$ ls -lh /var/lib/snapd/desktop/applications/*qown*
ls: cannot access '/var/lib/snapd/desktop/applications/*qown*': No such file or directory

$ sudo snap install qownnotes --channel=latest/edge
qownnotes (edge) 20.9.5 from Patrizio Bekerle (pbek) installed

$ ls -lh /var/lib/snapd/desktop/applications/*qown*
-rwxr-xr-x 1 root root 413 Sep 13 10:21 /var/lib/snapd/desktop/applications/qownnotes_qownnotes.desktop
```

It has only 1 Desktop file as we expected.

Unfortunately BOTH versions have a much worse problem. They don't fail to start:
```
# with latest/stable installed
$ qownnotes 
/snap/qownnotes/7428/bin/desktop-launch: line 595: /snap/qownnotes/7428/usr/bin/QOwnNotes: No such file or directory

# with latest/edge installed
$ qownnotes 
/snap/qownnotes/7432/bin/desktop-launch: line 595: /snap/qownnotes/7432/usr/bin/QOwnNotes: No such file or directory
```

**Comment by pbek** [comment]
> It seems the duplicate file is back. :( What changed since 20.9.4?

So far it wasn't gone in the stable channel.

## stable channel

- built by launchpad
- built from source archive hosted on tuxfamily

## edge channel

- build by snapcraft.io
- build from git repo directly

**Comment by pbek** [comment]
> Unfortunately BOTH versions have a much worse problem. They don't fail to start:

Now? That was what I feared in https://github.com/pbek/QOwnNotes/issues/1019#issuecomment-689801157 and must have come in before 20.9.5. Which version of QON did you use the last days?

**Comment by datumbox** [comment]
The struggle is getting real... :( Unfortunately snapcraft does not store the old versions to be able to check but the `snap` files seems to remain on the internal snap severs: https://api.snapcraft.io/api/v1/snaps/download/0Zs2bQCe724ZzBFiMYAYESxhhx85hj0W_7403.snap

So I downloaded that 7403 revision manually and installed it via `snap install 0Zs2bQCe724ZzBFiMYAYESxhhx85hj0W_7403.snap` and at least the [program starts. Unfortunately as per your comment, it shows 2 different desktop files. I could "binary search" it until I hit the version that worked AND deployed 1 desktop file. If you have any note / suggestion about the range please let me know because this is going to be messy...

---------

I also tried to see on the source what changed. I compare the `develop` branch which I assume is the latest with the commit `63fd7f4f73ab019e4428b1af9d945613c5acdf3e` which supposedly fixed the duplicate desktop problem:

```
git diff 63fd7f4f73ab019e4428b1af9d945613c5acdf3e..develop ":(exclude)*/languages/*"
....
diff --git a/build-systems/snap/snapcraft/snapcraft.yaml b/build-systems/snap/snapcraft/snapcraft.yaml
index c7294dd3b..502e76c63 100644
--- a/build-systems/snap/snapcraft/snapcraft.yaml
+++ b/build-systems/snap/snapcraft/snapcraft.yaml
@@ -61,6 +61,9 @@ parts:
     options:
       - CONFIG+=release
       - CONFIG+=snapcraft
+    override-build: |
+      echo Remove PBE.QOwnNotes.desktop
+      rm PBE.QOwnNotes.desktop
     build-packages:
       - qttools5-dev
       - build-essential
diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
index a5e9aa3b9..2fd05bf02 100644
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -67,7 +67,6 @@ parts:
     override-build: |
       echo Remove PBE.QOwnNotes.desktop
       rm src/PBE.QOwnNotes.desktop
-      ls src
     build-packages:
       - qttools5-dev
       - build-essential
diff --git a/src/build_number.h b/src/build_number.h
index ff0336219..fb7baa25b 100644
--- a/src/build_number.h
+++ b/src/build_number.h
@@ -1 +1 @@
-#define BUILD 759
+#define BUILD 760
diff --git a/src/version.h b/src/version.h
index 313359b27..1a169bb7f 100644
--- a/src/version.h
+++ b/src/version.h
@@ -1 +1 @@
-#define VERSION "20.9.4"
+#define VERSION "20.9.5"
```

I think the `override-build` in `./build-systems/snap/snapcraft/snapcraft.yaml` is to blame.

**Comment by pbek** [comment]
I'm currently building a new edge snap on snapcraft.io where I try to build the binary manually. Should be done soon.

**Comment by pbek** [comment]
...and I'm building a new stable snap on Launchpad without `override-build`.

**Comment by pbek** [comment]
Already failed, trying again...

**Comment by datumbox** [comment]
@pbek Everything works on edge (revision 7443):

```
$ sudo snap remove qownnotes
qownnotes removed

$ ls -lh /var/lib/snapd/desktop/applications/*qown*
ls: cannot access '/var/lib/snapd/desktop/applications/*qown*': No such file or directory

$ sudo snap install qownnotes --channel=latest/edge 
qownnotes (edge) 20.9.5 from Patrizio Bekerle (pbek) installed

$ ls -lh /var/lib/snapd/desktop/applications/*qown*
-rwxr-xr-x 1 root root 413 Sep 13 16:08 /var/lib/snapd/desktop/applications/qownnotes_qownnotes.desktop

$ snap list | grep qownnotes
qownnotes                20.9.5                      7443  latest/edge      pbek            -
```

**Comment by pbek** [comment]
AND you can run QOwnNotes? 😉

**Comment by datumbox** [comment]
Yes of course! :)

**Comment by pbek** [comment]
Great, I now updated the Launchpad Snap config. We'll see at the next release. 😁

**Comment by pbek** [comment]
## 20.9.6
- fixed building snap stable release

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by datumbox** [comment]
@pbek Sorry for the delay. It seems that the duplicate desktop files problem is back but everything else works as expected. I really don't understand why this is happening as we tested together the latest/edge version and it fixed the duplicate desktop files issue.

```
$ sudo snap remove qownnotes  
qownnotes removed

$ ls -lh /var/lib/snapd/desktop/applications/*qown*
ls: cannot access '/var/lib/snapd/desktop/applications/*qown*': No such file or directory

$ sudo snap install qownnotes --jailmode
qownnotes 20.9.6 from Patrizio Bekerle (pbek) installed

$ ls -lh /var/lib/snapd/desktop/applications/*qown*
-rwxr-xr-x 1 root root 417 Sep 17 22:52 /var/lib/snapd/desktop/applications/qownnotes_PBE.QOwnNotes.desktop
-rwxr-xr-x 1 root root 413 Sep 17 22:52 /var/lib/snapd/desktop/applications/qownnotes_qownnotes.desktop

$ diff /var/lib/snapd/desktop/applications/qownnotes_PBE.QOwnNotes.desktop /var/lib/snapd/desktop/applications/qownnotes_qownnotes.desktop
5c5
< Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/qownnotes_PBE.QOwnNotes.desktop /snap/bin/qownnotes
---
> Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/qownnotes_qownnotes.desktop /snap/bin/qownnotes
```

**Comment by pbek** [comment]
Thank you for the feedback. I don't understand it. The removal and build process are the same on snapcraft.io and launchpad. 😞

**Comment by pbek** [comment]
No `.desktop` file is processed in <https://launchpadlibrarian.net/497964873/buildlog_snap_ubuntu_bionic_amd64_qownnotes_BUILDING.txt.gz>

**Comment by datumbox** [comment]
@pbek If you [download](https://api.snapcraft.io/api/v1/snaps/download/0Zs2bQCe724ZzBFiMYAYESxhhx85hj0W_7455.snap) the snap on stable (rev 7455) and check folder /meta/gui/ in the archive you will find 2 desktop files. On the other hand if you [download](https://api.snapcraft.io/api/v1/snaps/download/0Zs2bQCe724ZzBFiMYAYESxhhx85hj0W_7457.snap) the snap on edge (rev 7457) you will get one desktop file. 

How do you deploy the snaps? Do you use travis or some other CI tool? Is there a chance that stable and edge have different configs on their releases?

**Comment by pbek** [comment]
> How do you deploy the snaps? Do you use travis or some other CI tool? Is there a chance that stable and edge have different configs on their releases?

https://github.com/pbek/QOwnNotes/issues/1019#issuecomment-691649567

**Comment by datumbox** [comment]
Maybe I see it. 

Your [deploy](https://github.com/pbek/QOwnNotes/blob/develop/snap/snapcraft.yaml#L69) xml has a "cd src" command while the [prod](https://github.com/pbek/QOwnNotes/blob/develop/build-systems/snap/snapcraft/snapcraft.yaml#L66) does not. Thus the file is not deleted on the latter case. Could you confirm?

**Comment by pbek** [comment]
That's because the prod uses the source archive, that is made from the `src` folder.

**Comment by datumbox** [comment]
I see, thanks for clarifying. 

I'm running out of ideas... What we see could be explained by a silent failure of the `rm` command but if you are sure that when any command fails the build breaks then I'm not sure where to go next. :(

**Comment by pbek** [comment]
## 20.9.9
- added a snap build to the release

The 20.9.9 release on https://github.com/pbek/QOwnNotes/releases will have a snap built on GitHub (currently building on https://github.com/pbek/QOwnNotes/runs/1150478719?check_suite_focus=true). Could you please test that, maybe I'll manage to put it into the snap store automatically.

**Comment by pbek** [comment]
Here it is: https://github.com/pbek/QOwnNotes/releases/download/untagged-76a03ac3c688da435913/QOwnNotes-amd64.snap

**Comment by datumbox** [comment]
> The 20.9.9 release on https://github.com/pbek/QOwnNotes/releases will have an amd64 snap built on GitHub.
Just to confirm you want me to download the snap from github and install it manually? If that's what you mean, I don't think this is possible without turning off the snap confinement which might return different results. Is it possible to upload it on snapstore?

> Here it is: https://github.com/pbek/QOwnNotes/releases/download/v20.9.9/QOwnNotes-x86_64.AppImage
You meant to link to the snap version, not the Appimage right?


BTW I did check the contents of the snap and it seems that it does not have the 2 icons inside. So it should be OK from that perspective.

**Comment by pbek** [comment]
> Is it possible to upload it on snapstore?

To do that I need to invest some more hours. I will only attempt that if the snap works as desired.

> You meant to link to the snap version, not the Appimage right?

sorry, my bad.

**Comment by datumbox** [comment]
Gotcha. Is there any way you can manually put that in snapcraft? Just trying to see if there is a way to avoid turning off the confinement while not adding much overload to you.

**Comment by pbek** [comment]
`sudo snap install --dangerous QOwnNotes-amd64.snap`

**Comment by datumbox** [comment]
@pbek lol. yeah that's what I wanted to avoid :P

Tested and it works like a charm. Only 1 desktop file, the favourites work fine etc. :)

**Comment by pbek** [comment]
> @pbek lol. yeah that's what I wanted to avoid :P

to my knowledge the confinement is still in place, the snap is just not coming from the store

> Tested and it works like a charm. Only 1 desktop file, the favourites work fine etc. :)

sounds great, thank you for testing!

**Comment by pbek** [comment]
## 20.9.10
- the AMD64 stable release snap of QOwnNotes will now be built by GitHub Actions to prevent
  two desktop files being deployed with the snap
    - the other architectures will still be built by Ubuntu Launchpad

**Comment by pbek** [comment]
There now is a new release building, could you please test it and report if it works for you?

**Comment by pbek** [comment]
The new stable snap is already in the store. 😉

**Comment by datumbox** [comment]
@pbek Sorry man, it's a very busy week. I just tested it. Everything works exactly as you expect: the favourites, the number of desktop files, the program, etc. I think it's time to close this epic saga ticket :) Good job and thank you!

**Comment by pbek** [comment]
Awesome! Thank you for your patience! 😅  We really should have made a different issue for this. But now I'll try to forget how much time was put into it. 😆
