### ISSUE TITLE
Preview of images inserted from other drives without copying them to the media library on Windows doesn't work

### ISSUE THREAD

**Issue by ostaith** [pbek/QOwnNotes#1785]
#### Expected behaviour

insert a image, and choose "Don't copy image to media folder", hope the image can display in note preview window.

#### Actual behaviour

the image can't display in note preview.

#### Steps to reproduce

when i insert a image, and choose "Don't copy image to media folder",
then note preview can't display the image.
i found the problem is this:
note preview add my notes root folder in the path.
for example, i set my note folder is "E:\Notes",
and the image i choose is from "G:\Temp\Pic.jpg".
finally note preview path is "E:\Notes\G:\Temp\Pic.jpg",
so note preview can't display the image.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[14:52:56] [warning] OpenType support missing for "SimSun", script 12
[14:52:56] [warning] OpenType support missing for "Arial", script 12
[14:52:56] [warning] OpenType support missing for "MS UI Gothic", script 12
[14:52:56] [warning] OpenType support missing for "Arial Unicode MS", script 12
[14:52:56] [warning] OpenType support missing for "Segoe UI Emoji", script 12
[14:52:56] [warning] OpenType support missing for "Segoe UI Symbol", script 12
[14:52:56] [warning] OpenType support missing for "Nirmala UI", script 12
[14:52:56] [warning] OpenType support missing for "SimSun", script 11
[14:52:56] [warning] OpenType support missing for "Arial", script 11
[14:52:56] [warning] OpenType support missing for "MS UI Gothic", script 11
[14:52:56] [warning] OpenType support missing for "Arial Unicode MS", script 11
[14:52:56] [warning] OpenType support missing for "Segoe UI Emoji", script 11
[14:52:56] [warning] OpenType support missing for "Segoe UI Symbol", script 11
[14:52:56] [warning] OpenType support missing for "Nirmala UI", script 11
[14:52:56] [warning] OpenType support missing for "SimSun", script 32
[14:52:56] [warning] OpenType support missing for "Arial", script 32
[14:52:56] [warning] OpenType support missing for "MS UI Gothic", script 32
[14:52:56] [warning] OpenType support missing for "Arial Unicode MS", script 32
[14:52:56] [warning] OpenType support missing for "Segoe UI Emoji", script 32
[14:52:56] [warning] OpenType support missing for "Segoe UI Symbol", script 32
[14:52:56] [warning] OpenType support missing for "Leelawadee UI", script 32
[14:52:56] [warning] OpenType support missing for "SimSun", script 13
[14:52:56] [warning] OpenType support missing for "Arial", script 13
[14:52:56] [warning] OpenType support missing for "MS UI Gothic", script 13
[14:52:56] [warning] OpenType support missing for "Arial Unicode MS", script 13
[14:52:56] [warning] OpenType support missing for "Segoe UI Emoji", script 13
[14:52:56] [warning] OpenType support missing for "Segoe UI Symbol", script 13
[14:52:56] [warning] OpenType support missing for "Nirmala UI", script 13
[14:52:56] [warning] OpenType support missing for "SimSun", script 20
[14:52:56] [warning] OpenType support missing for "Arial", script 20
[14:52:56] [warning] OpenType support missing for "MS UI Gothic", script 20
[14:52:56] [warning] OpenType support missing for "Arial Unicode MS", script 20
[14:52:56] [warning] OpenType support missing for "Segoe UI Emoji", script 20
[14:52:56] [warning] OpenType support missing for "Segoe UI Symbol", script 20
[14:52:56] [warning] OpenType support missing for "Nirmala UI", script 20
[14:52:56] [warning] OpenType support missing for "Microsoft YaHei UI", script 12
[14:52:56] [warning] OpenType support missing for "SimSun", script 12
[14:52:56] [warning] OpenType support missing for "Arial", script 12
[14:52:56] [warning] OpenType support missing for "MS UI Gothic", script 12
[14:52:56] [warning] OpenType support missing for "Arial Unicode MS", script 12
[14:52:56] [warning] OpenType support missing for "Segoe UI Emoji", script 12
[14:52:56] [warning] OpenType support missing for "Segoe UI Symbol", script 12
[14:52:56] [warning] OpenType support missing for "Nirmala UI", script 12
[14:52:56] [warning] OpenType support missing for "Microsoft YaHei UI", script 11
[14:52:56] [warning] OpenType support missing for "SimSun", script 11
[14:52:56] [warning] OpenType support missing for "Arial", script 11
[14:52:56] [warning] OpenType support missing for "MS UI Gothic", script 11
[14:52:56] [warning] OpenType support missing for "Arial Unicode MS", script 11
[14:52:56] [warning] OpenType support missing for "Segoe UI Emoji", script 11
[14:52:56] [warning] OpenType support missing for "Segoe UI Symbol", script 11
[14:52:56] [warning] OpenType support missing for "Nirmala UI", script 11
[14:52:56] [warning] OpenType support missing for "Microsoft YaHei UI", script 32
[14:52:56] [warning] OpenType support missing for "SimSun", script 32
[14:52:56] [warning] OpenType support missing for "Arial", script 32
[14:52:56] [warning] OpenType support missing for "MS UI Gothic", script 32
[14:52:56] [warning] OpenType support missing for "Arial Unicode MS", script 32
[14:52:56] [warning] OpenType support missing for "Segoe UI Emoji", script 32
[14:52:56] [warning] OpenType support missing for "Segoe UI Symbol", script 32
[14:52:56] [warning] OpenType support missing for "Leelawadee UI", script 32
[14:52:56] [warning] OpenType support missing for "Microsoft YaHei UI", script 13
[14:52:56] [warning] OpenType support missing for "SimSun", script 13
[14:52:56] [warning] OpenType support missing for "Arial", script 13
[14:52:56] [warning] OpenType support missing for "MS UI Gothic", script 13
[14:52:56] [warning] OpenType support missing for "Arial Unicode MS", script 13
[14:52:56] [warning] OpenType support missing for "Segoe UI Emoji", script 13
[14:52:56] [warning] OpenType support missing for "Segoe UI Symbol", script 13
[14:52:56] [warning] OpenType support missing for "Nirmala UI", script 13
[14:52:56] [warning] OpenType support missing for "Microsoft YaHei UI", script 20
[14:52:56] [warning] OpenType support missing for "SimSun", script 20
[14:52:56] [warning] OpenType support missing for "Arial", script 20
[14:52:56] [warning] OpenType support missing for "MS UI Gothic", script 20
[14:52:56] [warning] OpenType support missing for "Arial Unicode MS", script 20
[14:52:56] [warning] OpenType support missing for "Segoe UI Emoji", script 20
[14:52:56] [warning] OpenType support missing for "Segoe UI Symbol", script 20
[14:52:56] [warning] OpenType support missing for "Nirmala UI", script 20
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `周二 6月 9 14:53:41 2020`
**Version**: `20.6.2`
**Build date**: `Jun  6 2020`
**Build number**: `5755`
**Platform**: `windows`
**Operating System**: `Windows 10 (10.0)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.13.2`
**Qt Version (runtime)**: `5.13.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\xxxx\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `D:\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `zh_CN`
**Locale (interface)**: `en`
**Primary screen resolution**: `1920x1080`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `2`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `C:\Users\xxxx\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `Notes`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `E:\Document\Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `E:\Document\Notes\notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActionDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DictionaryManagerDialog/geometry** (QByteArray): `<binary data>`
**DictionaryManagerDialog/mainSplitterState** (QByteArray): `<binary data>`
**DistractionFreeMode/editorWidthMode** (int): `3`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (int): `25`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrainingSpaces** (QString): `true`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `G:/04 Temp`
**FileDialog/LastPath-InsertImage** (QString): `G:/04 Temp`
**FileDialog/LastPath-NoteHTMLExport** (QString): `G:/04 Temp`
**FileDialog/LastPath-PreviewHTMLFileExport** (QString): `G:/04 Temp`
**FileDialog/LastPath-SchemaExport** (QString): `E:/Software/App/QOwnNotes`
**FileDialog/LastPath-SettingsExport** (QString): `E:/Software/App/QOwnNotes`
**ImageDialog/disableCopying** (QString): `true`
**ImageDialog/geometry** (QByteArray): `<binary data>`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2020-06-09T14:39:08.511`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (QString): `true`
**LogWidget/debugLog** (QString): `true`
**LogWidget/fatalLog** (QString): `true`
**LogWidget/infoLog** (QString): `true`
**LogWidget/scriptingLog** (QString): `true`
**LogWidget/statusLog** (QString): `true`
**LogWidget/warningLog** (QString): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `32`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,11,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Microsoft YaHei UI,11,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Courier New,11,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font** (QString): `Microsoft YaHei UI,11,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `false`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MessageBoxOverride/calendar-cache-emptied** (int): `1024`
**MessageBoxOverride/delete-files** (int): `16384`
**MessageBoxOverride/layoutwidget-use-layout** (int): `16384`
**MessageBoxOverride/local-trash-notes-removed** (int): `1024`
**MessageBoxOverride/local-trash-remove-notes** (int): `16384`
**MessageBoxOverride/log-file-cleared** (int): `1024`
**MessageBoxOverride/readonly-mode-allow** (int): `16384`
**MessageBoxOverride/remove-note** (int): `16384`
**MessageBoxOverride/remove-notes** (int): `16384`
**MessageBoxOverride/remove-workspace** (int): `16384`
**NoteDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-1/NoteTabNameList** (QStringList): *empty*
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteFolder-1/allowDifferentNoteFileName** (QString): `false`
**NoteHistory-1** (QVariantList): `<variant list with 5 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `4`
**OrphanedAttachmentsDialog/geometry** (QByteArray): `<binary data>`
**OrphanedImagesDialog/geometry** (QByteArray): `<binary data>`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**Shortcuts/MainWindow-actionAutocomplete** (QString): `Ctrl+E`
**Shortcuts/MainWindow-actionJump_to_note_list_panel** (QString): `F6`
**Shortcuts/MainWindow-actionJump_to_note_subfolder_panel** (QString): `F7`
**Shortcuts/MainWindow-actionJump_to_note_text_edit** (QString): `F5`
**Shortcuts/MainWindow-actionJump_to_tags_panel** (QString): `F8`
**Shortcuts/MainWindow-action_Open_note_in_external_editor** (QString): `F4`
**Shortcuts/MainWindow-action_Settings** (QString): `F12`
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `true`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `true`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `qCb27wFPX4ph`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `true`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full-vertical`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): `en`
**internalIconTheme** (QString): `true`
**itemHeight** (int): `16`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (int): `7`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `false`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `true`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `0`
**notesPath** (QString): `E:/Document/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (QString): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `Xuwtf5E8zqcr`
**recentNoteFolders** (QStringList): `C:/Users/xxxx/Nextcloud/Notes`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `false`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2020-06-09T14.33.29, Note 2020-06-09T14.00.43, Note 2020-06-09T13.36.15, Note 2020-06-08T19.32.39, Note 2020-06-08T18.58.31, Note 2020-06-08T18.24.09`
**showMatches** (QString): `true`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `true`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (QString): `false`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionDelete_orphaned_images, actionManage_orphaned_attachments, action_Settings`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-DLVaZAgHb4Hg/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-DLVaZAgHb4Hg/windowState** (QByteArray): `<binary data>`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspace-qCb27wFPX4ph/name** (QString): `Full vertical`
**workspace-qCb27wFPX4ph/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-qCb27wFPX4ph/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `qCb27wFPX4ph`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\xxxx\AppData\Roaming`
**CommonProgramFiles**: `C:\Program Files (x86)\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `xxxx`
**ComSpec**: `C:\Windows\system32\cmd.exe`
**C_EM64T_REDIST11**: `C:\Program Files (x86)\Common Files\Intel\Shared Files\cpp\`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**FPS_BROWSER_APP_PROFILE_STRING**: `Internet Explorer`
**FPS_BROWSER_USER_PROFILE_STRING**: `Default`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\xxxx`
**LDMS_LOCAL_DIR**: `C:\Program Files (x86)\LANDesk\LDClient\Data`
**LOCALAPPDATA**: `C:\Users\xxxx\AppData\Local`
**NUMBER_OF_PROCESSORS**: `8`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JAR;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW`
**PROCESSOR_ARCHITECTURE**: `x86`
**PROCESSOR_ARCHITEW6432**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 142 Stepping 10, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `8e0a`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files (x86)`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules`
**PUBLIC**: `C:\Users\Public`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\Windows`
**TEMP**: `C:\Users\xxxx\AppData\Local\Temp`
**TMP**: `C:\Users\xxxx\AppData\Local\Temp`
**windir**: `C:\Windows`
</details>

**Comment by pbek** [comment]
Can you please fill out the issue template or use the issue assistant of QOwnNotes (in the *Help* menu). It's hard to know what we are talking about if you don't. 😆

**Comment by ostaith** [comment]
sorry to bother you. i wan't to use the issue assistant of QOwnNotes, and when i fill them, but i can't submit it. the "Next" button is gray.

**Comment by ostaith** [comment]
oh i got it, i don't fill the title. because there is "find issue" button, it confused me.

**Comment by pbek** [comment]
Thank you for reporting, I could reproduce that. It seems you have hit an edge case. QON tries to make links relative, which doesn't work under Windows with different drives.

**Comment by pbek** [comment]
## 20.6.3
- fixed preview of inserted images from another drive without copying them to the
  media library on Windows

**Comment by pbek** [comment]
There now is a new release, can you please try again inserting the image with the image dialog?

**Comment by ostaith** [comment]
hi pbek, it still not working:
![image](https://user-images.githubusercontent.com/34862369/84502036-2ddcef00-acea-11ea-9257-fb7dfc3c6d6a.png)

1. the 'Note preview' window just show the code but not the image.
2. and when i generate the raw HTML, the HTML code also not correct:
`<p>![ffff](file:///E:/Download/test 测试.jpg)</p>`,
it should be `<img src="file:///E:/Download/test 测试.jpg" alt="ffff"></p>`
pls check the [preview.zip](https://github.com/pbek/QOwnNotes/files/4770704/preview.zip)

3. and i find another big problem:
it need 2 return in 'Note edit', and then have 1 return in 'Note preview'.
please check my screen capture:
the 'aaaa' and 'ssss' is breaked in edit window, but not break in preview window.

**Comment by pbek** [comment]
> the 'Note preview' window just show the code but not the image.

It works if you are using your previous example `Pic.jpg` (please try that). It seems the markdown to html converter can't handle `测试`. Although it works if you let the image be inserted in the media library (because I remove such characters there).

Can you please open another issue for your `测试` problem. (@Waqar144, seems to be a md4c thing)

> the 'aaaa' and 'ssss' is breaked in edit window, but not break in preview window. and the 'ssss' and 'dddd' have 2 return break, then preview window have 1 return break.

That's no bug, That's markdown :)
If you want to force a newline you can for example add two spaces at the end of the line.

**Comment by pbek** [comment]
> but not break in preview window

You can also press `Shift + Return` at the end of the line, that will insert the two spaces for you.

**Comment by ostaith** [comment]
yes, for the `test.jpg` and `test测试.jpg`(no space), it working. but if the file name is`test 测试`(with space), it doesn't working.
ok, i'll open another issue.
