### ISSUE TITLE
Moving/copying a note to sub-folder

### ISSUE THREAD

**Issue by Maboroshy** [pbek/QOwnNotes#289]
I don't know if it's a question or an enhancement request.

I haven't yet found a way to copy a note to a sub-folder from within the app. 
Is there any, or is it in plans?

Maybe if there's no drag-n-drop there is going to be some clipboard-like moving/tagging.

**Comment by aizikil** [comment]
No doubt, this is a very wanted feature, at least for me.

**Comment by pbek** [comment]
## 16.08.10
- now you can **copy and move notes to a note subfolder** from the note 
  context menu

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by Maboroshy** [comment]
The app tells me that tagging will be lost. But I guess that's not true for sub-folders.

**Comment by pbek** [comment]
Eleven releases in August already, weather really has to suck in Graz. :)

Moved / copied notes will not be tagged. That would be a hell to implement because notes can be renamed in the background while moving or copying... I'm not planning to go into that hell.

**Comment by Maboroshy** [comment]
I'm working in the same direction now with [Bash-note](https://github.com/Maboroshy/Bash-note) developing the idea of filesystem-based note tagging. It's hell really. My head was exploding all the weekend and I've made very little code in the end.

If the moving or copying is the only problem I'd go for storing note hashes in the tag db you use. My case is much worse since I want to make tagging without any kind of a stored db.

**Comment by pbek** [comment]
But filesystem-based tagging will just work on that particular system with that filesystem, won't it?

**Comment by Maboroshy** [comment]
It's not some xattr based thing, that would be too easy and not really portable exactly as you say. 

I want hardcore plain text only tagging by using in-file markdown-like tags not shown in render and a script that make it all spinning. 

So you can tag the note and it will appear in tag sub-directory, or copy it to sub-directory and it will tag itself. Even that is not hard with symlinks/hardlinks but my phone running Linux with ext4 don't really work with them for some reason.

The hell begins when user make a change to a file in tag sub-directory and you can't use symlinks to translate it to source directory. And then knowing it's the mess that can be resolved by some hackery user make another change to the same file in another tag sub-folder and renames this file in third one. And the script will only see it all happened 5-6 hours later when files will be synced with Bash-note running machine,

That's where my weekend was ruined.

**Comment by pbek** [comment]
Oh man...
You always have to value the experience you have gained.

**Comment by Maboroshy** [comment]
The good thing is it's all going only in my head while I'm writing fancy scripts for fun.

**Comment by pbek** [comment]
One cannot stretch the word "fun" enough. Fun is the most important part.

**Comment by aizikil** [comment]
Houston we have a problem ! I created a folder and move there a few notes, but then I try to move them back in "Note folder" (I think it's better to rename it to default folder) it doesn't work. Tested on windows 10.

**Comment by pbek** [comment]
@aizikil, I will take a look at this.

**Comment by pbek** [comment]
will be fixed in 16.08.13

> I think it's better to rename it to default folder

This folder is called that way through the whole system. There is the note folder and since two month or so there are also note subfolders..

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by aizikil** [comment]
Yep it's not a problem ! So the thing is that I could move my old note back to note folder. But something is strange. Try to create a new note and move it to a new or old created folder and move back to root folder and then once again. On a third movement it bricks and don't allow me to move it more. Sometimes it doesn't work at all. I can make a video if you want and please note my setup. QOwnNotes uses folder which is feeded to owncloud client.

**Comment by pbek** [comment]
Are the note files properly moved at each step? Can you verify that in Explorer?

**Comment by pbek** [comment]
And what happens if you reload the note folder (note menu) when you can't move the notes any more?

**Comment by pbek** [comment]
@aizikil, I'll release a new version later today for you to test.

**Comment by aizikil** [comment]
@pbek, first of all, thank you for your work and app ! While I was moving around my note I got this message 
![3](https://cloud.githubusercontent.com/assets/10992663/17806751/0a3a52ac-660f-11e6-9c44-0e247f83bfee.JPG)
I pressed restore and received two notes, in note folder and in testing folder. I think I found it, thanks to you suggestion. Normally on a third movement, after you press confirmation move button, note move physically (in explorer) but GUI doesn't display changes and if you close app then reopen it, the GUI display a note in correct folder.

**Comment by pbek** [comment]
There seems to be some weirdness with moving files in Qt and the Qt filesystem watcher. I will release 16.08.14 soon.

**Comment by pbek** [comment]
## 16.08.14
- fixed a problem with copying/moving notes from a note subfolder to the
  main note folder where not all changes were viewed in the user interface

**Comment by pbek** [comment]
@aizikil, does that bring any improvements for you?

**Comment by aizikil** [comment]
@pbek, Thank you ! It works fine ! But small issue still exists, then 
folder is removed, changes are not displayed in GUI.

**Comment by pbek** [comment]
@aizikil, do you remove the folder in QOwnNotes or externally. Are they changes viewed if you reload the note folder manually in QOwnNotes?

**Comment by pbek** [comment]
## 16.08.15
- fixed a problem where the note list and the note subfolder list where
  not refreshed when a note or a note subfolder were removed

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by aizikil** [comment]
Hi, sorry for delay with answer. Right now I'm testing it on Fedora 24, 
I can check it on windows 10 on monday. So, the create function seems to 
work fine, but then I delete newly created folders, changes do not shown 
in GUI. Physically folders are deleted correctly. If I use "Reload note 
folder" option, GUI refreshes and display correct folder existence.

**Comment by pbek** [comment]
Did you use v16.08.15?

**Comment by Maboroshy** [comment]
Deleting sub-folders works for me on Linux.

**Comment by pbek** [comment]
@Maboroshy, thank you for testing.

> tags

good idea

**Comment by pbek** [comment]
## 16.08.16
- the warning about tags when copying or moving notes to a note
  subfolder will now be only displayed if one of the selected notes has
  a tag assigned

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by aizikil** [comment]
On windows 10 with QOwnNotes version 16.08.17 creating and deleting 
folders works fine, but still there are some minor issues.

First, if I trying to delete folder with sub-folders, in other words I 
have folder "new", inside it folder "new2" and inside it folder "new3", 
it won't delete all folders then I click remove confirmation button. It 
will delete "new3" folder, so I need to do it step by step.

Second, on all folders except "note folder" it's possible to edit number 
on the right side of folder. It's possible to put there letters and 
numbers. Didn't try anything else. Thanks.

**Comment by pbek** [comment]
@aizikil 

> First

Which folder have you selected when you try to delete it?

> Second

That even works with tags, very funny. :) Thank you for reporting!

**Comment by aizikil** [comment]
Folder "new". Thank you, for your outstanding support )

**Comment by pbek** [comment]
😄 

I will try to reproduce that, thank you.

**Comment by pbek** [comment]
@aizikil I created a note subfolder structure with notes, removed the top-most folder in QOwnNotes and the whole structure was gone. What did you do different?

**Comment by pbek** [comment]
I can't fix your 2nd finding too easily, because you only can set the edit flag for the whole QTreeWidgetItem in Qt (with all its columns).

**Comment by aizikil** [comment]
Regarding second finding, I can say that, at least we know it !

You need to create new folder, let's call it first, inside it, again, 
you need to create new folder let's call it second, and inside second 
folder you need to create third folder.

  * first

      * second
          o third





Then you should try to delete first folder.

**Comment by pbek** [comment]
I just created your folder structure with QOwnNotes and then removed the first folder in QOwnNotes. All folders were gone,
