### ISSUE TITLE
Notes recreated when changing Notes default folder

### ISSUE THREAD

**Issue by yvesle** [pbek/QOwnNotes#318]
Hi, thanks for the nice app but I encountered a weird problem when changing Notes default folder

**What I did**
I did some test creating notes on a dummy folder with a dozen files in it.
I then changed the default notes folder to my real one and did CTRL+MAJ+R (Reload the notes folder)
Only on default folder whas used. 
No sync set up with owncloud.
Windows 7

**What happened**
The notes panes displayed the notes in my new default older AND the ones in the old folder
I tried : Setttings>General>delete all application data and quit : no change
I tried : Setttings>General>reinit database, close QOwnnotes : no change
Looking in the new note folder I could see that the notes from the old folder where recreated in the new one
Deleting them from the notes panes solved the problem.

**What I expected**
Using CTRL+MAJ+R should refresh the notes panes and only display the notes in the newly configured folder.

Tell me if you need more information or tests on my part

Attached my debug info if needed
[QOwnNotes Debug Information.txt](https://github.com/pbek/QOwnNotes/files/471603/QOwnNotes.Debug.Information.txt)

**Comment by pbek** [comment]
From your settings I see: **currentNoteFolderId**: `0`
Do you currently have a note folder set as active in the `Note folder` settings? That settings might have been gone when you removed all your settings.

You currently only have on note folder, right? (`C:/Users/DMNL8761/Documents/Personnel/Documents`)
Have you checked the `Show subfolders in note list` checkbox for that note folder in the settings?

**Comment by yvesle** [comment]
Thank you for the swift reply. 

Indeed the setting was gone after the reset, I rechecked it.
The `Show subfolders in note list ` checkbox was set, this is indeed the reason I started testing QOwnNotes in the first place.

I did a second test as above and was not able to display the new files without using Setttings>General>delete all application data and quit` and setting the new default folder as "active".
I however did not see the old notes anymore, which is what I wanted.

Is this the way it was designed ? It seems a bit unintuitive since you are able to modify the notes folder on the fly in the settings and there is a "reload notes folder" option which suggests that the modifications would be picked up instantly.

Finally I noticed in my "old" folder that notes from the subdirectories were copied at the root of the default folder. It is really confusing.

**Comment by pbek** [comment]
I think I could reproduce what you are talking about. When one changes the note folder path of a note folder the note subfolder tree doesn't get updated, not even when you restart the app. It seems like noone did that before. If you have a 2nd note folder it will get updated if you switch to that and then back to your previous note folder.
Thank you for reporting!

Were you talking about that issue?
Can you please try to create a 2nd note folder and test if everything works fine when the note subfolder tree shows the correct folders?

**Comment by yvesle** [comment]
Indeed if I add a second note folder and switch between the two I do not encounter any problem and see the correct notes and folders
Granted, I had the issue because I was explicitely testing the application and I do not think I would need to do it again in normal use.

As a solution I can imagine not allowing to edit the path of a existing note folder. The UI is simple enough to delete it and recreate it when needed.

**Comment by pbek** [comment]
No, no, I will fix that. :) I just wanted to confirm that there is no other problem beside it.

**Comment by pbek** [comment]
## 16.09.7
- fixed a problem with note subfolders when changing the path of the
  currently active note folder in the settings

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by yvesle** [comment]
I tested it quickly.
Started by deleting all data and quit.
Changing the path of the active folder is working. I see the correct subfolder and notes. No more copied over notes from subfolder either.
However I stumbled on another bug. Every time I go to `Notes > configure note folder` it adds another blank folder and the one I set up looses the "active" status. It start with 2 blank folder and then piles up

![2016-09-15 10_07_37-parametres](https://cloud.githubusercontent.com/assets/22190569/18543341/9af170b6-7b2f-11e6-9a04-444e5674cae4.png)

![2016-09-15 10_25_54-parametres](https://cloud.githubusercontent.com/assets/22190569/18543364/c00ca780-7b2f-11e6-8657-26d7639bc13e.png)

**Comment by pbek** [comment]
I tried to do what you did but I could not reproduce your issue. Can you please post your debug output from the debug settings.

**Comment by yvesle** [comment]
There you go
I reproduced it but whith only one blank line, could not see more than one now.
- Go to Setting -> general, delete all data and quit
- Delete the sqli files in the notes folder (forgot to mention that)
- Restart QOwnNotes
- Select folder in wizzard
- no owncloud set up
- Disable data tracking in network wizzard
- (app opens)
- Got to Notes -> configure note folder
- see blank line
- selectioning the folder slected in the wizzard shows that the "active" checkbox is not ticked. (Notes taken do end up there however)

[QOwnNotes Debug Information.txt](https://github.com/pbek/QOwnNotes/files/474225/QOwnNotes.Debug.Information.txt)

**Comment by pbek** [comment]
I still can't reproduce that.
From your settings I see that you currently have no active note folder set. What happens if you set one?

**Comment by yvesle** [comment]
Nothing happens if I set the active note folder. New Notes were created in that folder with the box unchecked. they still do when I tick it.
I tried not deleting the "notes.sqlite" files : no change.

**Comment by pbek** [comment]
And you still get an empty note folder entry if you open the settings?
Can you please post an other debug settings output.

**Comment by yvesle** [comment]
At first I could not reproduce it either, really strange. And then after about 10 tries (data delete and quit in between) it reoccurs.
Strangely the name I gave to the folder I chose in the wizzard is maintained between wipe instead of "default" but I can see that the entry at HKEY_CURRENT_USER\Software\PBE\QOwnNotes is being wiped (not entirely though).
It is as if data is left behind that modify subsequent behaviour.
[QOwnNotes Debug Information 3.txt](https://github.com/pbek/QOwnNotes/files/474458/QOwnNotes.Debug.Information.3.txt)

**Comment by pbek** [comment]
At my tests under Windows the settings for QOwnNotes were (almost) cleared completely. I will try to clear them even more completely in the future. Where did you find the `QOwnNotes.sqlite`?

**Comment by pbek** [comment]
## 16.09.8
- took better care that some settings are getting stored after the
  `Clear app data and exit` button was pressed in the settings

Above also works in Windows, the registry for QOwnNotes was empty.
But for some reason the database was still present. Windows ignores the deletion of it.

**Comment by pbek** [comment]
I will see that the file really gets deleted, that surely will cause some problems under Windows...
for example no active note folder will be set... but I still cannot reproduce your "empty note folder will be created" problem... we will see what will happen after I fix the database file delete problem

**Comment by pbek** [comment]
## 16.09.8
- took better care that no settings are getting stored after the
  `Clear app data and exit` button was pressed in the settings and
  fixed a problem where the database file wasn't deleted under Windows

There now is a new release, could you please test it and report if the new features work for you?

**Comment by yvesle** [comment]
Hi
Deleting the setting works now. Registry is cleaner (only an empty QOwnotes folder left) but the `notes.sqli` files at the root of the note folder is still not deleted.
When relaunching after deletion, the note folder is set as "active", no blank lines anymore. The name of the notes folder is now default after deletion of the setting.
Deleting manually the notes.sqli files do not change the behaviour.
As far as I am concerned I think you nailed it. Thank you very much !

**Comment by pbek** [comment]
Thank you for testing! The `notes.sqlite` should not and will not be deleted, the data there is note-specific and not app-specific.
