### ISSUE TITLE
Undo/redo doesn't work in headers

### ISSUE THREAD

**Issue by szotsaki** [pbek/QOwnNotes#520]
1. Create a new note and type in a new header (like `## My header`)
2. Press Ctrl+Z to undo the last typed word (`ḣeader`).

Ctrl+Z doesn't work in this case.

**Comment by pbek** [comment]
I cannot reproduce that.
Maybe your note folder (and the note with it) got reloaded, then of course there wouldn't be a history in the note text edit...

Can you please post the output from the debug settings and maybe some log output if you enable the log widget.

**Comment by szotsaki** [comment]
I can reproduce it in any new note as well.

1. Have a new note in a subdirectory named „Gépi tanulás”
2. Paste the following into the note:

  ```
Note 2017-02-15T09.23.53
========================

### asdasdasd
  ```

3. Add some letters after „asdasd” and try to Ctrl+Z it.

I don't see anything in the log window. Debug output is in issue #516.

**Comment by pbek** [comment]
I can confirm that undo doesn't work in headlines that start with `#`. No new note or sub-folders are needed to test this. Headlines like 

```markdown
Note 2017-02-13T12.38.0
========================
```

work for me.
So far I've no idea what is causing this.

**Comment by pbek** [comment]
I've still no idea, since the undo process is controlled by the [QTextEdit](http://doc.qt.io/qt-5/qtextedit.html).

**Comment by pbek** [comment]
It is caused by setting a block format to the headlines in `MarkdownHighlighter::setCurrentBlockMargin`. Could be a Qt bug...

**Comment by bepolymathe** [comment]
This problem has been solved. It works fine for me.

**Comment by pbek** [comment]
I still have the same problem. @bepolymathe, can you please post your first block of the *QOwnNotes Debug Information* from the Debug settings to let me see what system you are using?.

**Comment by pbek** [comment]
I've:

## General Info
**Current Date**: `Fr. Juli 28 09:21:11 2017`
**Version**: `17.07.7`
**Build date**: `Jul 26 2017`
**Build number**: `359`
**Platform**: `linux`
**Operating System**: `KDE neon User Edition 5.10`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.5.1`
**Qt Version (runtime)**: `5.9.1`
**Portable mode**: `no`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: `en`

**Comment by bepolymathe** [comment]
Hi @pbek 

I have this :

## General Info

**Current Date**: `ven. juil. 28 09:29:00 2017`
**Version**: `17.07.7`
**Build date**: `Jul 26 2017`
**Build number**: `359`
**Platform**: `linux`
**Operating System**: `Fedora 26 (Workstation Edition)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `OBS`
**Qt Version (build)**: `5.7.1`
**Qt Version (runtime)**: `5.7.1`
**Portable mode**: `no`
**Settings path / key**: `/home/manu/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/manu/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `fr_FR`
**Locale (interface)**: *empty*
**Icon theme**: `Adwaita`
**Notes in current note folder**: `20`
**Enabled scripts**: `4`

**Comment by bepolymathe** [comment]
Different Qt Version...

**Comment by pbek** [comment]
But it neither works for me on:

## General Info

**Version**: `17.07.7`
**Build date**: `Jul 26 2017`
**Build number**: `3114`
**Platform**: `macosx`
**Operating System**: `macOS Sierra (10.12)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Travis CI`
**Qt Version (build)**: `5.9.1`
**Qt Version (runtime)**: `5.9.1`
**Portable mode**: `no`
**Qt Debug**: `0`

**Comment by bepolymathe** [comment]
It's strange.

**Comment by yodayeti** [comment]
I experience the same.

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Mo Aug 14 12:53:03 2017`
**Version**: `17.08.4`
**Build date**: `Aug 13 2017`
**Build number**: `3160`
**Platform**: `windows`
**Operating System**: `Windows 7 SP 1`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.7.1`
**Qt Version (runtime)**: `5.7.1`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\LENOVO\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `E:\Programs\PortableApps\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `de_DE`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `108`
**Enabled scripts**: `0`

**Comment by pbek** [comment]
## 17.09.0
- margins for headlines in the note editor are now disabled, because Qt bugs 
  are causing multiple problems with them
    - they prevent "undo" in headlines
      (for [Issue #520](https://github.com/pbek/QOwnNotes/issues/520))
    - they generate invisible lines at the end of a note
      (for [Issue #667](https://github.com/pbek/QOwnNotes/issues/667))
    - the cause a crash when reaching the invisible lines when highlighting of
      the current line is turned on (for [Issue #701](https://github.com/pbek/QOwnNotes/issues/701))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by ludenticus** [comment]
I've tested release 17.09.0, and it solves this issue. Only caveat: `Ctrl + Z` undoes a whole line. I can't recollect if this was the standard behavior

**Comment by pbek** [comment]
Great, thank you for testing!
I can't control the actual undo-mechanism of the QTextEdit, that is done by Qt internally.
