### ISSUE TITLE
QOwnNotes Markdown view uses wrong encoding on WIndows

### ISSUE THREAD

**Issue by janhenke** [pbek/QOwnNotes#8]
Any note containing UTF-8 letters appears broken in the Markdown view. It looks like the Markdown view uses a legacy encoding, as one UTF-8 letter is displayed as 3 random glyphs apparently interpreting each byte according to some Windows code page.

**Comment by janhenke** [comment]
The issue seems specific to Windows. Opening the same note on Linux uses correct UTF-8 encoding.

**Comment by pbek** [comment]
Thank you for reporting. Markdown rendering is done by https://github.com/hoedown/hoedown.
I'll see if using a new version will change anything. QOwnNotes currently uses 3.0.1, the latest is 3.0.3...

Sadly I currently don't have access to a Windows 8 installation.

**Comment by pbek** [comment]
Did you try using it on a local filesystem?

**Comment by janhenke** [comment]
The files are on the local file system (C:\Users\Jan\OwnCloud\Notes).
I am not familiar with that library, maybe it needs to be told to use the correct encoding? On Linux it definitely works, but Linux usually used UTF-8 as the default.

**Comment by pbek** [comment]
Could you please provide me with a text file that causes problems?

**Comment by janhenke** [comment]
For example a simple German sentence: 
```
Äpfel liegen auf der Straße
```
In the Markdown view it results in this String:
```
Ã„pfel liegen auf der StraÃŸe 
```

Another example is this Vietnamese word:
```
#Đào
```

Resulting in this broken String:
```
ÄaÌ€o
```

**Comment by pbek** [comment]
Seems to be a problem with the hoedown library, I updated to 3.0.3, but the problem is still there...

**Comment by janhenke** [comment]
So can you raise the issue with the library devs? The current situation makes the Markdown view unusable on Windows.

**Comment by pbek** [comment]
I think I found a solution, it's in the latest git commit... Should be fixed in build 27 for Windows. Can you confirm that it works for you now?

**Comment by janhenke** [comment]
It is much better indeed (btw the Window stil says build 26). Đào is still broken though, but different from before, it is now displayed as

```
?a?o 
```

It is definitely better.

**Comment by pbek** [comment]
That's not really better. :) And it has to say Build 27, I will check again.

**Comment by pbek** [comment]
I definitely don't have the issue with the this version under Windows 7: http://www.qownnotes.org/content/download/75/365/version/17/file/QOwnNotes.zip
(I build it again, now it really says build 27. I guess the new version header file got ignored last time)

Do you have any improvement?

**Comment by janhenke** [comment]
Well it is better since it is less broken than before. I downloaded it yesterday from the website, where the download section said build 27, but the title said build 26. The link above gave me build 27 now though.

It looks like the issue now is that certain characters are replaced with question marks. That seems the case mostly with letters from the Vietnamese alphabet. For example ```mười``` (which just means 10). Both ```ư``` and ```ơ``` are not displayed correctly. Also ```đ``` is equally broken. Having them replaced by a question mark is definitely an improvement, but I hope we can figure out a way to make it work correctly.

**Comment by pbek** [comment]
You may try build 28 now.
http://www.qownnotes.org/content/download/75/365/version/18/file/QOwnNotes.zip

**Comment by janhenke** [comment]
Build 28 seems to work now. I hope that fixes the problems for everyone. As a matter of curiosity, what exactly was the cause?

**Comment by pbek** [comment]
string conversion, character encoding conversion, string length calculation... lots of nasty stuff :)
